[project]
title = "Semaphore"
copyright = "2021-2023 Association of Universities for Research in Astronomy, Inc. (AURA)"

[project.python]
package = "semaphore"

[project.openapi]
openapi_path = "_static/openapi.json"
doc_path = "api"

[project.openapi.generator]
function = "semaphore.main:create_openapi"

[sphinx]
rst_epilog_file = "_rst_epilog.rst"
